apiVersion: v1
kind: Pod
metadata:
  name: servicio-hernan-pod
  labels:
    app: servicio-hernan
spec:
  containers:
    - name: servicio-hernan-container
      image: herdavid/servicehernan:v1.0
      ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: servicio-hernan-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    app: servicio-hernan