# servicioeyder-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: servicioeyder
  labels:
    app: servicioeyder
spec:
  containers:
  - name: servicioeyder
    image: eydersantiago/serviceorquesta:latest 
    ports:
    - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: servicioeyder
spec:
  selector:
    app: servicioeyder
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
