apiVersion: v1
kind: Pod
metadata:
  name: servicio-orquestalab-pod
  labels:
    app: servicio-orquestalab
spec:
  containers:
    - name: servicio-orquestalab-container
      image: juleipssy/servicio-api:latest
      ports:
        - containerPort: 8001

---

apiVersion: v1
kind: Service
metadata:
  name: servicio-orquestalab-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8001
      nodePort: 30081
      protocol: TCP
  selector:
    app: servicio-orquestalab