apiVersion: v1
kind: Pod
metadata:
  name: santi-service-pod
  labels:
    app: santi-service
spec:
  containers:
    - name: santi-service-container
      image: santiagosanchez03/santi-service:latest
      ports:
        - containerPort: 3001

---

apiVersion: v1
kind: Service
metadata:
  name: santi-service-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3001
      protocol: TCP
  selector:
    app: santi-service