apiVersion: v1
kind: Pod
metadata:
  name: servicioluis
  labels:
    app: servicioluis
spec:
  containers:
    - name: servicioluis
      image: luisgabriel/servicioluisnode:latest
      ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: servicioluis
spec:
  selector:
    app: servicioluis
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
